# Generated by Django 5.2.6 on 2025-10-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_options_alter_commentlike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='是否回复评论'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='reply_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='回复评论id'),
        ),
    ]
