# Generated by Django 5.2.6 on 2025-10-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
